language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
script:
  bundle exec rake test
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
