language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3
  - 2.4
  - 2.5
sudo: false
script: 
  bundle exec rake test
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
