language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
sudo: false
services:
  - mongodb
script: 
  bundle exec rake test
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
