language: ruby
cache: bundler
rvm:
  - 2.1.2
sudo: false
services:
  - mongodb
script: 
  bundle exec rake test
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
